version: '3.4'
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stagiop
      - MYSQL_USER=stagiop
      - MYSQL_PASSWORD=h3lloWorld
    ports:
      - 3326:3306

  # mongodb:
  #   image: mongo
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_DATABASE=stagiop
  #   ports:
  #     - 27017:27017

  nginx:
    restart: always
    depends_on:
      - api
      - app
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/usr/ts2/api
      - /usr/ts2/api/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=mysql
      - TYPEORM_PORT=3306
      - TYPEORM_USERNAME=stagiop
      - TYPEORM_PASSWORD=h3lloWorld
      - TYPEORM_DATABASE=stagiop
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_ENTITIES=src/domain/entity/*.js
      - TYPEORM_LOGGING=true
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_HOST=${MONGODB_HOST}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_PROCESS_CLIEND_ID=${KAFKA_PROCESS_CLIEND_ID}
    ports:
      - 5000:5000

  app:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    volumes:
      - ./app:/usr/ts2/app
      - /usr/ts2/app/node_modules

  consumer:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./kafka-consumer
    volumes:
      - ./kafka-consumer:/usr/ts2/kafka-consumer
      - /usr/ts2/kafka-consumer/node_modules
    environment:
      - KAFKA_CLIENTID=ts2-consumer-app
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_GROUPID=ts2-group
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
